---
- name: 开放端口：Kubernetes API server
  become: yes
  firewalld:
    zone=public
    port=6443/tcp
    permanent=true
    state=enabled

- name: 开放端口：etcd server client API
  become: yes
  firewalld:
    zone=public
    port=2379-2380/tcp
    permanent=true
    state=enabled

- name: 开放端口：Kubelet API、kube-scheduler、kube-controller-manager
  become: yes
  firewalld:
    zone=public
    port=10250-10252/tcp
    permanent=true
    state=enabled

- name: 复制镜像包
  copy:
    src: "{{k8s_master_images}}"
    dest: "/tmp/k8s-master-images/"

- name: 获取所有tar镜像文件路径
  find:
    paths: "/tmp/k8s-master-images/"
    patterns: "*.tar"
  register: rs

- name: 导入镜像
  become: yes
  shell: "docker load < {{item.path}}"
  with_items:
    - "{{rs.files}}"
