---
- name: 开放端口：Kubelet API
  become: yes
  firewalld:
    zone=public
    port=10250/tcp
    permanent=true
    state=enabled

- name: 开放端口：NodePort Services
  become: yes
  firewalld:
    zone=public
    port=30000-32767/tcp
    permanent=true
    state=enabled

- name: 复制镜像包
  copy:
    src: "{{k8s_worker_images}}"
    dest: "/tmp/k8s-worker-images/"

- name: 获取所有tar镜像文件路径
  find:
    paths: "/tmp/k8s-worker-images/"
    patterns: "*.tar"
  register: rs

- name: 导入镜像
  become: yes
  shell: "docker load < {{item.path}}"
  with_items:
    - "{{rs.files}}"
