---
- name: 禁用swap
  become: yes
  mount:
    path: swap
    state: absent
    backup: yes

- name: 开放端口：Kubelet API
  become: yes
  firewalld:
    zone=public
    port=10250/tcp
    permanent=true
    state=enabled

- name: 开放端口：dashboard
  become: yes
  firewalld:
    zone=public
    port=8443/tcp
    permanent=true
    state=enabled

- name: 复制镜像包
  copy:
    src: "{{minikube_images}}"
    dest: "/tmp/minikube-images/"

- name: 获取所有tar镜像文件路径
  find:
    paths: "/tmp/minikube-images/"
    patterns: "*.tar"
  register: rs

- name: 导入镜像
  become: yes
  shell: "docker load < {{item.path}}"
  with_items:
    - "{{rs.files}}"

- name: 复制kubectl和minikube
  become: yes
  copy:
    src: "{{minikube_bin}}"
    dest: "/usr/local/bin/"
    mode: a+x

- name: 复制VirtualBox安装文件
  copy:
    src: "{{virtual_box_rpms}}"
    dest: "/tmp/virtual-box-rpms/"

- name: 获取VirtualBox安装文件路径
  find:
    paths: "/tmp/virtual-box-rpms/"
    patterns: "*.rpm"
  register: fs

- name: 取所有文件
  set_fact:
    rpm_path: "{{item.path}}"
  with_items: "{{fs.files}}"
  register: fp

- name: 取所有文件path属性
  set_fact:
      rpm_list: "{{ fp.results | map(attribute='ansible_facts.rpm_path') | list }}"

- name: 安装VirtualBox
  become: yes
  yum:
    name: "{{rpm_list}}"
    state: present

#- name: 启动集群
#  shell: "minikube start"
#  environment:
#    CHANGE_MINIKUBE_NONE_USER: 'true'
#    MINIKUBE_HOME: '$HOME'
#    KUBECONFIG: '$HOME/.kube/config'
