---

- name: minikube start
  become: 'true'
  shell: 'http_proxy=192.168.1.10:1087 sudo -E /usr/local/bin/minikube start --vm-driver=none'
  environment:
    CHANGE_MINIKUBE_NONE_USER: 'true'
    MINIKUBE_HOME: '$HOME'
    KUBECONFIG: '$HOME/.kube/config'
